---
- name: Install dependency
  become: true
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Adding GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding docker repo
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  become: true
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start docker 
  become: true
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Adding user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

# handlers:
# - name: restart docker
#   service: 
#     name: docker 
#     state: restarted